---
# Networkutils

# ```ansible-playbook initial_server.yml -u root --ask-vault-pass```


- name: Create deploy user on networkutils.
  hosts: ansible-client3
  roles:
        
    - role: lnovara.deploy-user
      user_name: abel
      user_groups:
        # - users
        # - docker
      public_keys:
        - ~/.ssh/ServerAccess.pub
      enable_passwordless_sudo: false

    - { role: geerlingguy.security,
        security_sudoers_passwordless: abel,
        security_autoupdate_mail_to: abelmatser+security@gmail.com
      }

    - { role: geerlingguy.docker,
        docker_users: abel
      }
    # - { role: geerlingguy.docker_arm,
    #     docker_users: []
    #   }

    - { role: geerlingguy.git
      }

    - role: lnovara.mosquitto
      mosquitto_config:
        # psk_file: /etc/mosquitto/mosquitto.psk,
        password_file: /etc/mosquitto//mosquitto.passwd
      mosquitto_auth_users:
        - name: abel_mosquitto
          state: present
          password: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                30663363333866653839663137643434616662316538633663383537633836376637623762663134
                3963373566393163313630396166393430663839343434300a663766373530376263363666396238
                34663661616535626338613430363634393533643639373265383262616637373665303161653132
                3762323661373164630a326663303837396166386539663931353733613563396234626261346464
                3861