---

- name: Create deploy user on networkutils.
  hosts: ansible-client3
  roles:
        
    - role: lnovara.deploy-user
      user_name: abel
      user_groups: []
        # users
        # abel
      public_keys:
        - ~/.ssh/ServerAccess.pub
      enable_passwordless_sudo: false

    # - { role: juju4.adduser,
    #     adduser_user_name: abel2,
    #     adduser_user_home: '/home/abel2',
    #     adduser_sudoroot: true,
    #     adduser_shell: '/bin/bash',
    #     adduser_expires: -1,
    #     adduser_groups: [],
    #     adduser_public_keys: ~/.ssh/ServerAccess.pub,
    #     enable_passwordless_sudo: false}

    # - name: add user directly in sudoers if no defined admin group
    #   lineinfile:
    #     dest: /etc/sudoers
    #     regexp: "^{{ adduser_user_name }} ALL"
    #     line: "{{ adduser_user_name }} ALL=(ALL) ALL"
    #     state: present
    #     become: yes
    #     backup: yes
    #     validate: 'visudo -cf %s'

    # - { role: singleplatform-eng.users,
    #     users_create_per_user_group: true,
    #     users_group: users,
    #     users_default_shell: /bin/bash,
    #     users_create_homedirs: true,
    #     users: abel,
    #     authorized_keys_file: ".ssh/authorized_keys"
    # }

    # - role: grog.user
    #   # user_list: abel
    #   user_list:
    #     - name: abel
    #   user_list_host: []
    #   user_list_group: []
    #   user_shell: '/bin/sh'
    #   user_system: no
    #   user_update_password: always

    # - role: grog.management-user,
    #   # become: yes
    #   management_user_key: "{{ lookup('file', '~/.ssh/ServerAccess.pub') }}"

    #   management_user_settings:
    #     name: management
    #     comment: Ansible
    #     shell: '/bin/bash'
    #     authorized_keys:
    #       - key: "{{ management_user_key }}"
    #         exclusive: yes
    #     sudo:
    #       hosts: ALL
    #       as: ALL
    #       commands: ALL
    #       nopasswd: yes
    


    - { role: geerlingguy.security,
        security_sudoers_passwordless: abel,
        security_autoupdate_mail_to: abelmatser+security@gmail.com
      }

    - { role: geerlingguy.docker,
        docker_users: abel
      }
    # - { role: geerlingguy.docker_arm,
    #     docker_users: []
    #   }

    - { role: geerlingguy.git
      }