---
# Networkutils

# ```ansible-playbook initial_server.yml -u root --ask-vault-pass```

- name: Create deploy user on networkutils.
  hosts: rpi4
  become: yes
  roles:

    ## Install programs
    # python-pip
    # (docker.io)



    - role: grog.management-user
      management_user_settings:
        name: abel
        comment: Ansible
        shell: '/bin/bash'
        authorized_keys:
          - key: "{{ lookup('file', '~/.ssh/ServerAccess.pub') }}"
          # keys meerdere devices toevoegen
            exclusive: yes  # Whether to remove all other non-specified keys from the authorized_keys file.
            path: '/home/abel/.ssh/authorized_keys'
        sudo:
          hosts: ALL
          as: ALL
          commands: ALL
          nopasswd: yes

    - role: grog.user
      user_list:
        - name: docker
          groups:
            - video  # Jellyfin
        - name: ubuntu
          state: absent
        - name: pi
          state: absent
      user_remove: yes
      user_shell: '/bin/bash'
      user_ssh_key_file:
      user_system: no
      user_update_password: always
    
    - role: geerlingguy.security
      # security_ssh_permit_root_login: "yes"  # default: no
      security_sudoers_passwordless: abel
      security_autoupdate_mail_to: abelmatser+security@gmail.com

    # - role: geerlingguy.docker
    #   become: yes
    #   docker_users: docker
    - role: geerlingguy.docker_arm  # No release candidate yet.
      docker_users: docker

      ## Werkt nog niet
      ## install docker-compose
      ## install pip docker
    # - role: ./deploy-jellyfin
    #   tags: 'jellyfin'

    - role: geerlingguy.git

    # - role: lnovara.mosquitto
    #   mosquitto_config:
    #     # psk_file: /etc/mosquitto/mosquitto.psk,
    #     password_file: /etc/mosquitto//mosquitto.passwd
    #   mosquitto_auth_users:
    #     - name: abel_mosquitto
    #       state: present
    #       password: !vault |
    #             $ANSIBLE_VAULT;1.1;AES256
    #             30663363333866653839663137643434616662316538633663383537633836376637623762663134
    #             3963373566393163313630396166393430663839343434300a663766373530376263363666396238
    #             34663661616535626338613430363634393533643639373265383262616637373665303161653132
    #             3762323661373164630a326663303837396166386539663931353733613563396234626261346464
    #             3861

    ## Instal ufw
    # exceptions:
    # ssh, mosquitto, dockerports

    ## Containers

