---
- name: pip remove docker-py
  pip:
    name: docker-py
    state: absent

- name: pip install docker
  pip:
    name: docker
    # state: absent

# https://github.com/docker/docker-py/issues/1502
# sudo cp -r ~/.local/lib/python2.7/site-packages/backports/ssl_match_hostname/ /usr/lib/python2.7/dist-packages/backports

- name: Create Jellyfin container
  docker_container:
    pull: yes
    restart_policy: always
    state: started
    # state: absent
    # env_file:
    #   -.env
    image: linuxserver/jellyfin
    name: "jellyfin"
    # state: present
    # env_file:
    #   - .env
    volumes:
      - /mnt/toshiba/docker/config/jellyfin:/config
      - /home/docker/jellyfin_cache:/cache
      - "/mnt/toshiba/docker/videos/:/media:ro"
      #- ${DOCKERDIR}/jellyfin:/config
      #- ${MEDIADIR}/:/media
      - /opt/vc/lib:/opt/vc/lib
    ports:
      - "9007:8096"
    # environment:
    env:
      # - PUID=${PUID}
      # - PGID=${PGID}
      # - TZ=${TZ}
        PUID: "1002"  # docker
        PGID: "1002"  # docker
        TZ: "Europe/Amsterdam"
    devices:
      - /dev/dri:/dev/dri  # Intel GPU: vaapi
      - /dev/vc-mem:/dev/vc-mem  # Raspberry Pi MMAL: OpenMax H264 decode
      - /dev/vchiq:/dev/vchiq  # Raspberry Pi OpenMax video encoding
      - /dev/video10:/dev/video10  # Raspberry Pi V4L2 video encoding
      - /dev/video11:/dev/video11  # Raspberry Pi V4L2 video encoding
      - /dev/video12:/dev/video12  # Raspberry Pi V4L2 video encoding
    # restart: always
    # labels:



# - name: pip install docker-compose
#   pip:
#     name: docker-compose
#     state: absent

# - name: Tear down existing services
#   # docker_compose:
#   docker_service:
#     project_src: dc-jellyfin.yml
#     state: absent

# - name: Create and start services
#   # docker_compose:
#   docker_service:
#     project_src: dc-jellyfin.yml
#     state: present
#   register: output

# - debug:
#     var: output

# - name: Run `docker-compose up` again
#   docker_compose:
#     project_src: dc-jellyfin.yml
#     build: no
#   register: output