---
# - name: Run database container
#   docker_container:
#     name: 'database'
#     image: 'docker.io/centos/postgresql-96-centos7'
#     state: 'started'
#     env:
#       POSTGRESQL_USER: 'user'
#       POSTGRESQL_PASSWORD: 'password'
#       POSTGRESQL_DATABASE: 'my_db'
#   register: db_cont_metadata

- ping:

- name: Re-create a redis container
  # docker_container:
  #   name: myredis
  #   image: redis
  #   command: redis-server --appendonly yes
  #   state: present
  #   recreate: yes
  #   exposed_ports:
  #     - 6379
  #   volumes_from:
  #     - mydata


  docker_container:
    # env_file:
    #   -.env
    image: linuxserver/jellyfin
    name: "jellyfin"
    state: present
    # env_file:
    #   - .env
    volumes:
      - /mnt/toshiba/docker/config/jellyfin:/config
      - /home/docker/jellyfin_cache:/cache
      - "/mnt/toshiba/docker/videos/:/media:ro"
      #- ${DOCKERDIR}/jellyfin:/config
      #- ${MEDIADIR}/:/media
      - /opt/vc/lib:/opt/vc/lib
    ports:
      - "9007:8096"
    # environment:
    env:
      # - PUID=${PUID}
      # - PGID=${PGID}
      # - TZ=${TZ}
        PUID: "1002"  # docker
        PGID: "1002"  # docker
        TZ: "Europe/Amsterdam"
    devices:
      - /dev/dri:/dev/dri  # Intel GPU: vaapi
      - /dev/vc-mem:/dev/vc-mem  # Raspberry Pi MMAL: OpenMax H264 decode
      - /dev/vchiq:/dev/vchiq  # Raspberry Pi OpenMax video encoding
      - /dev/video10:/dev/video10  # Raspberry Pi V4L2 video encoding
      - /dev/video11:/dev/video11  # Raspberry Pi V4L2 video encoding
      - /dev/video12:/dev/video12  # Raspberry Pi V4L2 video encoding
    # restart: always
    # labels:

# pip install docker


# - name: Tear down existing services
#   # docker_compose:
#   docker_service:
#     project_src: dc-jellyfin.yml
#     state: absent

# - name: Create and start services
#   # docker_compose:
#   docker_service:
#     project_src: dc-jellyfin.yml
#     state: present
#   register: output

# - debug:
#     var: output

# - name: Run `docker-compose up` again
#   docker_compose:
#     project_src: dc-jellyfin.yml
#     build: no
#   register: output